<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="EPPLKRAW0483" ignored="0" name="Calculator Tests" tests="6" failures="1" timestamp="28 Oct 2017 23:38:45 GMT" time="141.34" errors="0">
  <testcase name="verifyingTheDivision" time="24.02" classname="appium.wonkyCalculatorTests.tests.CalculatorDivisionTests"/>
  <testcase name="verifyingTheMultiplication" time="23.368" classname="appium.wonkyCalculatorTests.tests.CalculatorMultiplicationTests"/>
  <testcase name="verifyingThePowerOfTwo" time="21.028" classname="appium.wonkyCalculatorTests.tests.CalculatorPowerTests">
    <failure type="java.lang.AssertionError" message="expected [Result: 12] but found [Result: 9]">
      <![CDATA[java.lang.AssertionError: expected [Result: 12] but found [Result: 9]
	at appium.wonkyCalculatorTests.tests.CalculatorPowerTests.verifyingThePowerOfTwo(CalculatorPowerTests.java:27)
... Removed 34 stack frames]]>
    </failure>
  </testcase> <!-- verifyingThePowerOfTwo -->
  <testcase name="verifyingTheSquareRoot" time="22.009" classname="appium.wonkyCalculatorTests.tests.CalculatorSquareRootTests"/>
  <testcase name="verifyingTheSubstraction" time="23.102" classname="appium.wonkyCalculatorTests.tests.CalculatorSubstractionTests"/>
  <testcase name="verifyingTheSum" time="27.779" classname="appium.wonkyCalculatorTests.tests.CalculatorSumTests"/>
</testsuite> <!-- Calculator Tests -->
